"""create_user_sessions_table

Revision ID: 004eb1d924e4
Revises: 1042ab95a788
Create Date: 2026-07-15 23:32:30.759841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004eb1d924e4'
down_revision: Union[str, Sequence[str], None] = '1042ab95a788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='JWT token 的 SHA256 hash'),
    sa.Column('device_info', sa.String(length=255), nullable=True, comment='设备信息'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('last_used_at', sa.DateTime(), nullable=False, comment='最后使用时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='注销时间，NULL 表示未注销'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index('ix_user_sessions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_id')
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_revoked_at'))

    op.drop_table('user_sessions')
    # ### end Alembic commands ###
