"""add_audit_logs_table

Revision ID: 1042ab95a788
Revises: cba88a127d03
Create Date: 2026-07-15 23:22:38.406259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1042ab95a788'
down_revision: Union[str, Sequence[str], None] = 'cba88a127d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作者用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型，如 ENABLE_USER'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标对象类型，如 user'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='目标对象ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='变更详情 JSON'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='操作者IP地址'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_operator_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
