""" add_audit_log_user_agent_and_status

Revision ID: e71287e0ff42
Revises: b08b874abe12
Create Date: 2026-07-16 23:59:28.646680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71287e0ff42'
down_revision: Union[str, Sequence[str], None] = 'b08b874abe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True, comment='客户端 User-Agent'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='SUCCESS', nullable=False, comment='结果状态：SUCCESS / FAILURE'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
