"""Base Retriever — abstract interface for all document retrievers.

Every concrete retriever (Chroma, Qdrant, Milvus, hybrid, …) MUST inherit
from :class:`BaseRetriever` and implement :meth:`retrieve`.
"""
from abc import ABC, abstractmethod


class BaseRetriever(ABC):
    """Abstract base class for document retrievers.

    Each implementor receives a query embedding (already generated by
    the embedding service) and returns raw search results as a list of
    dicts.  Score filtering and context formatting are handled upstream
    by :class:`RetrievalPipeline`.
    """

    @abstractmethod
    async def retrieve(
        self,
        embedding: list[float],
        knowledge_base_id: int,
        top_k: int = 5,
    ) -> list[dict]:
        """Search for documents matching the given query embedding.

        Args:
            embedding: The query embedding vector (from embedding service).
            knowledge_base_id: Filter results to this knowledge base.
            top_k: Maximum number of results to return (default 5).

        Returns:
            A list of result dicts.  Each dict MUST contain at least:
            ``{"document_id": int, "filename": str, "chunk_index": int,
            "text": str, "score": float}``.
        """
        ...